# Generated by Django 5.2.3 on 2025-06-28 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'permissions': [('can_inactivate', 'Может блокировать пользователя')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='Как мы будем к Вам обращаться', max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ0-9_ ]+$', message='Имя может содержать только буквы, цифры и пробелы')], verbose_name='Имя для отображения'),
        ),
    ]
