# Generated by Django 5.2.3 on 2025-06-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('nutrition', 'Дневник питания'), ('sport', 'Спорт'), ('water', 'Вода'), ('snacks', 'Перекусы'), ('bad_habits', 'Вредные привычки'), ('good_habits', 'Полезные привычки'), ('gratitude', 'Дневник благодарности'), ('custom', 'Свое поле')], max_length=50, verbose_name='Тип поля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартное поле')),
            ],
            options={
                'verbose_name': 'Дополнительное поле',
                'verbose_name_plural': 'Дополнительные поля',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('entry_text', models.TextField(verbose_name='Основной текст')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSelectedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field_name', models.CharField(blank=True, max_length=100, verbose_name='Название своего поля')),
                ('fields', models.ManyToManyField(to='diary.customfield', verbose_name='Выбранные поля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка полей пользователя',
                'verbose_name_plural': 'Настройки полей пользователей',
            },
        ),
    ]
