# Generated by Django 5.2.3 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name='Порядок сортировки',
                help_text='Число для определения порядка полей (меньше - выше)'
            ),
        ),
    ]
