# Generated by Django 5.2.3 on 2025-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_add_default_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Дополнительное поле', 'verbose_name_plural': 'Дополнительные поля'},
        ),
        migrations.AlterModelOptions(
            name='diaryentry',
            options={},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('checkbox', 'Галочка'), ('select', 'Выбор из списка'), ('nutrition', 'Дневник питания'), ('sport', 'Спорт'), ('water', 'Вода'), ('snacks', 'Перекусы'), ('bad_habits', 'Вредные привычки'), ('good_habits', 'Полезные привычки'), ('gratitude', 'Дневник благодарности'), ('custom', 'Свое поле')], max_length=50, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='userselectedfields',
            name='fields',
            field=models.ManyToManyField(blank=True, to='diary.customfield', verbose_name='Выбранные поля'),
        ),
    ]
